    spring.application.name=filmyflix

# ---- Database ----
spring.datasource.url=jdbc:postgresql://dpg-d9ss5p67bikc73a5k620-a.singapore-postgres.render.com:5432/filmyflix
spring.datasource.username=filmyflix_user
spring.datasource.password=99egK0tdjbBna9J3crAvKWJIQTNwnN52
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- TMDB ----
tmdb.api.key=038de8279ff3104a701429ad3e569c86
tmdb.base.url=https://api.themoviedb.org/3

# ---- JWT ----
jwt.secret=filmyflixSuperSecretKeyChangeThisInProduction123456
jwt.expiration=86400000

# ---- Server ----
server.port=8080
# ---- Google OAuth2 ----
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile