    spring.application.name=filmyflix

# ---- Database ----
spring.datasource.url=jdbc:mysql://localhost:3306/filmyflix
spring.datasource.username=root
spring.datasource.password=Pawan@12342005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ---- TMDB ----
tmdb.api.key=038de8279ff3104a701429ad3e569c86
tmdb.base.url=https://api.themoviedb.org/3

# ---- JWT ----
jwt.secret=filmyflixSuperSecretKeyChangeThisInProduction123456
jwt.expiration=86400000

# ---- Server ----
server.port=8080
# ---- Google OAuth2 ----
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile